### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cssRules' of null

### ISSUE THREAD

**Issue by rbecheras** [twalker/inline-styles#1]
Trying to use `inlineStyle(iFrameDocument)`, throwing the folowing error:

```
Uncaught TypeError: Cannot read property 'cssRules' of null          inline-styles.js:66
Editor.setContent   @   tinymce.js:32422
Editor.load @   tinymce.js:32284
Editor.initContentBody  @   tinymce.js:31695
Editor.init @   tinymce.js:31428
(anonymous function)    @   tinymce.js:31175
(anonymous function)    @   tinymce.js:8830
each    @   tinymce.js:2925
callback.loadScripts.loadScripts    @   tinymce.js:8829
(anonymous function)    @   tinymce.js:8822
done    @   tinymce.js:8664
```

cf. code : 

```
function inlineStyle(elStyle){
  //console.log('elStyle', elStyle)
  var doc = elStyle.ownerDocument;
  var rules = elStyle.sheet.cssRules;       // Line 66
  if(!rules){
    console.error('stylesheet rules cannot be read from ', elStyle.href);
    return;
  }
```

**Comment by twalker** [comment]
Is your css file served from a different domain?

From an [mdn document](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet)

> In some browsers, if a stylesheet is loaded from a different domain, calling cssRules result in SecurityError.

**Comment by rbecheras** [comment]
Not at all, its a iframe that contain local or same domain stylesheets.

As you can see, the line

```
    console.error('stylesheet rules cannot be read from ', elStyle.href);
```

is not reached, and the exeption is thrown from line 66: 

```
  var rules = elStyle.sheet.cssRules;       // Line 66
```

**Comment by twalker** [comment]
I presume your using the `iframe.contentDocument` like in the demo:
https://github.com/twalker/inline-styles/blob/master/demo/demo.js#L28

Can you provide a way to reproduce the error for troubleshooting?

If not, try running the `/demo` folder and modifying the example to match your circumstances.
